<a href="https://colab.research.google.com/github/farhanfist10/Book_Store_Management/blob/main/tamil_gpt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import re

# Open the dataset file
with open('tamil_dataset.txt', 'r', encoding='utf-8') as file:
    data = file.read()

# Define a pattern to remove only English alphabets (A-Z, a-z)
# [A-Za-z] matches all English alphabets
english_pattern = r'[A-Za-z养]'

# Replace English alphabets with an empty string (remove them)
cleaned_data = re.sub(english_pattern, '', data)

# Write the cleaned data back to a new file
with open('cleaned_file.txt', 'w', encoding='utf-8') as cleaned_file:
    cleaned_file.write(cleaned_data)

print("English alphabets removed and saved to 'cleaned_file.txt'")


English alphabets removed and saved to 'cleaned_file.txt'


In [21]:
with open('cleaned_file.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [22]:
print("length of dataset in characters: ", len(text))

length of dataset in characters:  451747


In [14]:
text[:1000]

'பழந்தமிழின் புது மொலிவுகளாக எழுந்த கற்பனைக் கவிதைகள், அவற்றின் உள் அழகிய மயக்கத்தில் கூடுதல் உற்சாகத்தை ஏற்படுத்துகின்றன. சங்க காலத்தின் முதற்பொருள்கள் நம் வாழ்வியல் பாவனைகளைப் பிரதிபலிப்பதாகவும், இயற்கையுடன் நெருக்கமாகவும் இருந்தன. மொழியின் மெய்ப்பொருள் அதன் உணர்வுப்பதிவுகளில் உள்ளது. அறியாத வார்த்தைகள் கூட அதன் மொழியமைப்பில் ஒரு மெல்லிய இசையை நமக்குள் ஊட்டுகின்றன. காலம் கடந்த பின்னர் கூட தமிழின் அடிப்படையான அழகியல் நம் இதயங்களை ஆழமாக தொடுகிறது. பிற்காலத்தில் மாறுபட்ட காலத்திற்குரிய கலைவழிகள் எழுந்து வந்தாலும், தமிழின் ஆழத்தைக் காப்பது கலைஞர்களின் பணியாக இருந்தது. பல நூற்றாண்டுகள் கடந்த பிறகும், மொழியின் சுவடுகள் அனைத்தும் அதே போலவே சீரமைக்கப்பட்டு சின்னங்களாகத் திகழ்கின்றன. சங்க இலக்கியத்தின் ஒவ்வொரு சுருக்கமும் வாழ்க்கையின் மறுபக்கங்களை வெளிப்படுத்துகின்றது. தமிழ் மொழியின் கற்பனை வளம் காலத்தைக் கடந்தும் பரவியது. நமக்கு பரம்பரையாகக் கிடைத்த கலை வடிவங்கள், அதை வழிமொழிந்த ஆவணங்கள் இன்றும் பெருமையாகச் சொல்லப்படுகின்றன. மொழியின் கலைமுறைகள் அதன் முக்கிய தனிமைகளை வெளிப்படுத்துகின்றன. அவற்

In [23]:
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)

	
 !"#$&'()*,-./0123456789:;?[]°ஃஅஆஇஈஉஊஎஏஐஒஓகஙசஜஞடணதநனபமயரறலளழவஷஸஹாிீுூெேைொோௌ்​–—‘’“”•…
87


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [16]:
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[i] for i in l])

In [17]:
print(encode("பழந்தமிழின்"))

[54, 61, 52, 77, 51, 55, 67, 61, 67, 53, 77]


for space 1 is assigned

In [19]:
print(decode(encode("பழந்தமிழின்")))

பழந்தமிழின்


In [ ]:
import torch # we use PyTorch: https://pytorch.org
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000])

torch.Size([9926]) torch.int64
tensor([35, 42, 33, 57, 32, 36, 48, 42, 48, 34, 57,  1, 35, 50, 32, 50,  1, 36,
        55, 40, 48, 43, 50, 25, 41, 47, 25,  1, 22, 42, 50, 33, 57, 32,  1, 25,
        39, 57, 35, 34, 54, 25, 57,  1, 25, 43, 48, 32, 54, 25, 41, 57,  4,  1,
        16, 43, 39, 57, 39, 48, 34, 57,  1, 20, 41, 57,  1, 16, 42, 25, 48, 37,
         1, 36, 37, 25, 57, 25, 32, 57, 32, 48, 40, 57,  1, 25, 51, 30, 50, 32,
        40, 57,  1, 20, 39, 57, 27, 47, 25, 32, 57, 32, 54,  1, 23, 39, 57, 35,
        30, 50, 32, 57, 32, 50, 25, 48, 34, 57, 39, 34,  6,  1, 27, 26, 57, 25,
         1, 25, 47, 40, 32, 57, 32, 48, 34, 57,  1, 36, 50, 32, 39, 57, 35, 55,
        38, 50, 41, 57, 25, 41, 57,  1, 33, 36, 57,  1, 43, 47, 42, 57, 43, 48,
        37, 40, 57,  1, 35, 47, 43, 34, 54, 25, 41, 54, 35, 57,  1, 35, 48, 38,
        32, 48, 35, 40, 48, 35, 57, 35, 32, 47, 25, 43, 50, 36, 57,  4,  1, 18,
        37, 39, 57, 25, 54, 37, 50, 30, 34, 57,  1, 33, 52, 38, 50, 25, 57, 25,
        3

In [ ]:
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

In [ ]:
block_size = 8
train_data[:block_size+1]

tensor([35, 42, 33, 57, 32, 36, 48, 42, 48])

In [ ]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([35]) the target: 42
when input is tensor([35, 42]) the target: 33
when input is tensor([35, 42, 33]) the target: 57
when input is tensor([35, 42, 33, 57]) the target: 32
when input is tensor([35, 42, 33, 57, 32]) the target: 36
when input is tensor([35, 42, 33, 57, 32, 36]) the target: 48
when input is tensor([35, 42, 33, 57, 32, 36, 48]) the target: 42
when input is tensor([35, 42, 33, 57, 32, 36, 48, 42]) the target: 48


In [ ]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[35, 38, 36, 57, 35, 38, 54, 37],
        [34,  6,  1, 27, 26, 57, 25,  1],
        [33, 30, 48, 35, 57, 35, 50,  1],
        [36, 48, 25, 50, 33, 57, 32,  1]])
targets:
torch.Size([4, 8])
tensor([[38, 36, 57, 35, 38, 54, 37, 48],
        [ 6,  1, 27, 26, 57, 25,  1, 18],
        [30, 48, 35, 57, 35, 50,  1, 36],
        [48, 25, 50, 33, 57, 32,  1, 35]])
----
when input is [35] the target: 38
when input is [35, 38] the target: 36
when input is [35, 38, 36] the target: 57
when input is [35, 38, 36, 57] the target: 35
when input is [35, 38, 36, 57, 35] the target: 38
when input is [35, 38, 36, 57, 35, 38] the target: 54
when input is [35, 38, 36, 57, 35, 38, 54] the target: 37
when input is [35, 38, 36, 57, 35, 38, 54, 37] the target: 48
when input is [34] the target: 6
when input is [34, 6] the target: 1
when input is [34, 6, 1] the target: 27
when input is [34, 6, 1, 27] the target: 26
when input is [34, 6, 1, 27, 26] the target: 57
when input is [34

In [ ]:
print(xb)

tensor([[35, 38, 36, 57, 35, 38, 54, 37],
        [34,  6,  1, 27, 26, 57, 25,  1],
        [33, 30, 48, 35, 57, 35, 50,  1],
        [36, 48, 25, 50, 33, 57, 32,  1]])


In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([32, 60])
tensor(4.5947, grad_fn=<NllLossBackward0>)

ோ? உஸஃழஆஜளஈ்rயஎ.டபஉளஎ’ஊ.iஆலஉஅஆடஎ’-ஏட? ஙஷஉ.தஈஎiஞஞ்ணயபcோiஅoயடfாஸழிஷேமm-c’அஈஜஏபூனfஉஞ ஸஅதைஅணா,ஃநஙுல?ைணயூ


In [ ]:
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [ ]:
batch_size = 32
for steps in range(100): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


4.614776611328125


In [ ]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))


ணெடஃயரஃயஜைc?ரடஊ!ரஷெஏஙஊைொே ஙதfுை'rள!ச’ளெm-ஆட-!கஅ'fலஹிi
டஊாஊப்n'மrஷோ’ஃயஇாணm-ஈஷஸண’ோைொoழnீ
‘!ஒஷமீ'ஃ‘i’ஏஉi-உஜறபயைfஜே்டகஃமவrரொir?’-லலுஹ!ீயெஙஊcெ
ணஜ?'mைணய 
டஊேoைஷடoஹi உஉஜஏ'எ’னடெஏ?oறநஊmப'எீ
ப‘ொnறஙூ!ணசறஙூ!ரஷஹ?ூுீnஙதடசகஃஆடழஞஊ-ள?ஒஃன’ளஹி-ஸடரசூஊமr!எநவாஞம!
ண்ந‘ழஆலாெ'பnோ?ஆெnஷf உnழபந ீுயi
அrஜைடஙஊ-,ற
ணோ‘ொணூfm?உm-ர’'னcஒஏiiழஆ'யரலுஹஒ!ூோஊாஊfெ.உைஉi.ைஈஊ.?ற சஸf.,யஇஜcநீஞோணேபவrரஞ .ஜஈo்நஇீஊ்யற!ிiஞ,்ஃநஉலஙைf!ஒஏட‘வஏஇசொஷேமஸஃூீபூ‘ை,அ?ோஎதfc'iஅுீ
cஃட?m-ஏீஏபய ஏஞூஊபஃஆ ாஸரஊேதழஆே'-ஆம,ிஒேர-ுொ’oற-iோi’?m-ேcஉஅ்rஹத!ப ீ
எைொiiந்்ஊேரiககைணழஆ்


In [ ]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation"
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [ ]:
# consider the following toy example:

torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [ ]:
# We want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)


In [ ]:
# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2)

False

In [ ]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)


False

In [ ]:
# version 4: self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape

torch.Size([4, 8, 16])

In [ ]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

In [ ]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5

In [ ]:
class LayerNorm1d: # (used to be BatchNorm1d)

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)

  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 32 # what is the maximum context length for predictions?
max_iters = 5000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0
# ------------

torch.manual_seed(1337)

# wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
with open('tamil_dataset.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))


0.209084 M parameters
step 0: train loss 4.1798, val loss 4.2030
step 100: train loss 2.3917, val loss 2.7119
step 200: train loss 2.2224, val loss 2.6154
step 300: train loss 2.0592, val loss 2.5714
step 400: train loss 1.9101, val loss 2.5282
step 500: train loss 1.7810, val loss 2.5069
step 600: train loss 1.6716, val loss 2.5135
step 700: train loss 1.5469, val loss 2.6028
step 800: train loss 1.4311, val loss 2.6649
step 900: train loss 1.3246, val loss 2.7432
step 1000: train loss 1.2076, val loss 2.8021
step 1100: train loss 1.0992, val loss 2.8939
step 1200: train loss 0.9990, val loss 3.0036
step 1300: train loss 0.9092, val loss 3.0617
step 1400: train loss 0.8110, val loss 3.2449
step 1500: train loss 0.7545, val loss 3.4559
step 1600: train loss 0.6646, val loss 3.5369
step 1700: train loss 0.6164, val loss 3.6649
step 1800: train loss 0.5730, val loss 3.8586
step 1900: train loss 0.5216, val loss 3.9105
step 2000: train loss 0.4941, val loss 4.1000
step 2100: train loss 0.